### ISSUE TITLE
如果是 uuid 这种有现成工具库的功能复制粘贴和用现成的工具库如何选择？

### ISSUE THREAD

**Issue by SuperBigSaltedFish** [toyobayashi/snippets#1]
如题

**Comment by toyobayashi** [comment]
@SuperBigSaltedFish  并不是所有项目都会用 npm，也并不是所有项目都会用打包器。现成的工具库可能包含了大量你不需要的代码，比如这个仓库里的objectid，如果要用库，你就得装 bson，而且bson还不能直接用在浏览器上。

**Comment by toyobayashi** [comment]
如果是图方便，减少无用代码，或者就单纯不想为了用一个简单的功能把一整个库塞进你的 node_modules，就选择复制粘贴吧

**Comment by SuperBigSaltedFish** [comment]
了解了
